version: '3.3'

services:
  fireflyiii:
    image: jc5x/firefly-iii:latest
    volumes:
      - firefly_iii_export:/var/www/firefly-iii/storage/export
      - firefly_iii_upload:/var/www/firefly-iii/storage/upload
    env_file: firefly-env
    ports:
      - 80:80
    depends_on:
      - fireflydb
  
  fireflydb:
    image: postgres:10-alpine
    env_file:
      postgres-env
    volumes:
      - firefly_iii_db:/var/lib/postgresql/data

volumes:
   firefly_iii_export:
   firefly_iii_upload:
   firefly_iii_db:

